name: dsm-glossary-update
on:
  push:
    branches:
      - 'add-glossary'
    paths:
      - docs/glossary.tsv
jobs:
  dsm_glossary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          python script/dsm_glossary.py